import { ImageResponse } from "next/og";
import { COLORS } from "@ledgeur/ui";
import { SITE } from "@/lib/site";

// The Open Graph / social-share image (1200×630), generated by next/og.
//
// Colours come from the design tokens rather than being retyped, which is how
// the previous version ended up on a palette the site no longer used — and
// with the wrong letter in the logo mark. It rendered a "P".
//
// next/og renders through satori, which has no access to the site's stylesheet
// and only uses fonts handed to it explicitly — a `fontFamily: "serif"` here
// silently does nothing. Rather than fetch and embed Fraunces on every render
// for one image, this leans on the default face and carries the brand through
// colour and composition instead.
export const alt = `${SITE.name} — ${SITE.tagline}`;
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OgImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: 88,
          background: COLORS.paper,
          fontFamily: "sans-serif",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 20 }}>
          <div
            style={{
              width: 64,
              height: 64,
              borderRadius: 16,
              background: COLORS.ink,
              color: COLORS.paper,
              fontSize: 38,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            L
          </div>
          <div style={{ fontSize: 38, color: COLORS.text }}>{SITE.name}</div>
        </div>

        <div
          style={{
            marginTop: 44,
            fontSize: 62,
            color: COLORS.text,
            lineHeight: 1.08,
            maxWidth: 940,
            display: "flex",
          }}
        >
          Every meeting, on the record. None of it on our servers.
        </div>

        <div style={{ marginTop: 30, fontSize: 27, color: COLORS.textMuted, maxWidth: 940, lineHeight: 1.4 }}>
          Transcription and speaker separation run in your browser. Name a voice once and it is
          recognised in every meeting after.
        </div>

        <div style={{ marginTop: 40, display: "flex", gap: 12 }}>
          {["Open source · MIT", "Nothing is uploaded", "Free forever for one person"].map((chip) => (
            <div
              key={chip}
              style={{
                fontSize: 20,
                color: COLORS.accentStrong,
                background: COLORS.accentSoft,
                borderRadius: 999,
                padding: "8px 20px",
              }}
            >
              {chip}
            </div>
          ))}
        </div>
      </div>
    ),
    { ...size },
  );
}
