import { ImageResponse } from "next/og";
import { COLORS } from "@ledgeur/ui";
import { SITE } from "@/lib/site";

// The Open Graph / social-share image (1200×630), generated by next/og.
//
// Colours come from the design tokens rather than being retyped, which is how
// a previous version ended up on a palette the site no longer used. next/og
// renders through satori, which has no access to the site's stylesheet and
// only uses fonts handed to it explicitly, so this leans on the default face
// and carries the brand through colour and composition instead.
export const alt = `${SITE.name} — ${SITE.tagline}`;
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

const CHIPS: readonly [string, string, string][] = [
  ["Open source · MIT", COLORS["iris-strong"], COLORS["iris-soft"]],
  ["Nothing is uploaded", COLORS["mint-strong"], COLORS["mint-soft"]],
  ["Free forever for one person", COLORS["sky-strong"], COLORS["sky-soft"]],
];

export default function OgImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: 88,
          background: COLORS.surface,
          fontFamily: "sans-serif",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 20 }}>
          {/* The mark: three bars on an iris tile. */}
          <div style={{ width: 64, height: 64, borderRadius: 18, background: COLORS.brand, display: "flex", alignItems: "center", justifyContent: "center", gap: 6 }}>
            <div style={{ width: 9, height: 16, borderRadius: 5, background: "#fff" }} />
            <div style={{ width: 9, height: 42, borderRadius: 5, background: "#fff" }} />
            <div style={{ width: 9, height: 26, borderRadius: 5, background: "#fff" }} />
          </div>
          <div style={{ fontSize: 38, fontWeight: 700, color: COLORS["ink-text"], letterSpacing: -1 }}>{SITE.name}</div>
        </div>

        <div
          style={{
            marginTop: 44,
            fontSize: 64,
            fontWeight: 700,
            letterSpacing: -2,
            color: COLORS["ink-text"],
            lineHeight: 1.06,
            maxWidth: 960,
            display: "flex",
          }}
        >
          Every meeting, on the record. None of it on our servers.
        </div>

        <div style={{ marginTop: 28, fontSize: 27, color: COLORS.muted, maxWidth: 940, lineHeight: 1.4 }}>
          Transcription and speaker separation run on your device. Name a voice once and it is
          recognised in every meeting after.
        </div>

        <div style={{ marginTop: 40, display: "flex", gap: 12 }}>
          {CHIPS.map(([chip, fg, bg]) => (
            <div key={chip} style={{ fontSize: 20, fontWeight: 600, color: fg, background: bg, borderRadius: 999, padding: "8px 20px" }}>
              {chip}
            </div>
          ))}
        </div>
      </div>
    ),
    { ...size },
  );
}
