import type { Post } from "./post-types";

// SEO content set 1 — alternatives + platform how-tos. Targets validated
// keywords (live Google Ads, US, 2026-06-14).
export const SET_1: Post[] = [
  {
    slug: "open-source-granola-alternative",
    title: "The Best Open-Source Granola Alternative in 2026",
    description: "Granola is a great AI notepad, but it's closed-source, macOS-only and cloud-based. Here's the open-source, private, cross-platform alternative.",
    keyword: "open source granola",
    date: "2026-06-14",
    updated: "2026-09-25",
    readMins: 8,
    body: [
      { type: "p", text: "Granola popularised the idea of an AI notepad that quietly listens to your meeting and turns your sparse notes into a polished summary. It's well-designed — but it's closed source, macOS-first, and it processes your meeting audio in its cloud. For a lot of people and most companies, that last point is a dealbreaker." },
      { type: "h2", text: "What an open-source Granola alternative should do" },
      { type: "ul", items: ["Transcribe meetings accurately, including the other participants — not just you", "Keep audio on your device so sensitive conversations never hit a third-party server", "Work on any OS, not just macOS", "Be free for individuals, with a clear, non-predatory upgrade path for teams", "Be genuinely open source so you can audit or self-host it"] },
      { type: "h2", text: "How Ledgeur compares" },
      { type: "p", text: "Ledgeur runs OpenAI's Whisper model directly in your browser using WebGPU or WebAssembly. The audio is captured from your meeting tab and microphone and transcribed locally — nothing is uploaded. It's MIT-licensed, so you can read the code, fork it, or run it inside your own network. And because the compute happens on your machine, it's free for individuals with no minute caps." },
      { type: "h2", text: "When Granola still makes sense" },
      { type: "p", text: "If you live entirely in macOS, want a native menu-bar app, and you're comfortable with cloud processing, Granola is polished and worth the subscription. If you care about privacy, cross-platform support, or open source — or you just don't want to pay per seat — Ledgeur is the better fit." },
      { type: "h2", text: "Make the comparison on a real meeting" },
      { type: "p", text: "Do not decide this from a feature grid. Pick a recorded call that has interruptions, names, a screen share and at least two speakers. Run it through each product, then compare three things: whether the transcript got the names right, whether you can tell who said what, and whether the final note gives you a decision you can trace back to the recording. Those are the moments when a meeting note either earns its place or becomes another document nobody trusts." },
      { type: "p", text: "Then inspect the route the audio takes. An open-source label alone does not say where a hosted service processes a recording, and a privacy claim alone does not tell you whether a company can change its terms later. For Ledgeur, the useful test is mundane: record in a browser, open its network panel, and look for audio leaving the page. The source code is there to inspect too. That is more useful than a promise buried in a comparison page." },
      { type: "h2", text: "The trade-offs are real" },
      { type: "ul", items: ["Local transcription uses your machine's CPU or GPU. On an older laptop, the first model load and long recordings can take more patience than a cloud upload.", "A local-first tool cannot make collaboration appear by magic. Decide where you will share a final note and who should be allowed to see the underlying transcript.", "Open source gives you an audit path and an exit route; it does not remove the need to check versioning, backups and access controls in your own organisation."] },
    ],
    faqs: [
      { question: "Is an open-source meeting assistant automatically private?", answer: "No. Check where the deployed product sends audio and transcripts, which services it calls, and whether you can inspect or run the relevant code yourself." },
      { question: "Can I use Ledgeur if I do not use a Mac?", answer: "Ledgeur runs in a modern browser, so it is not limited to a single desktop operating system. Check the current browser support page before a critical meeting." },
    ],
    sources: [
      { label: "OpenAI Whisper model card", href: "https://github.com/openai/whisper/blob/main/model-card.md" },
      { label: "Ledgeur source repository", href: "https://github.com/maxbeech/ledgeur" },
    ],
  },
  {
    slug: "best-ai-meeting-assistant-2026",
    title: "How to Choose an AI Meeting Assistant in 2026",
    description: "A practical guide to picking an AI meeting assistant — what features matter, the privacy trade-offs of bots and cloud transcription, and how to compare them.",
    keyword: "ai meeting assistant",
    date: "2026-06-13",
    readMins: 7,
    body: [
      { type: "p", text: "An AI meeting assistant records your calls, transcribes them and writes the notes so you can pay attention instead of typing. The category exploded over the last two years, and the tools now differ less on transcription quality than on how they handle your data." },
      { type: "h2", text: "The features that actually matter" },
      { type: "ul", items: ["Transcription accuracy on real, noisy calls — not just clean demo audio", "Whether a bot has to join the meeting (and show up in the participant list)", "Where audio is processed: your device, or the vendor's cloud", "How notes are structured: summary, decisions, action items", "Export and ownership — can you take your data with you?"] },
      { type: "h2", text: "The bot problem" },
      { type: "p", text: "Most assistants join your call as a participant bot. That's visible to everyone, it needs calendar access to do it automatically, and it means your audio streams to a third party. A browser-based assistant like Ledgeur captures the meeting tab's audio directly, so there's no bot and no cloud upload." },
      { type: "h2", text: "Privacy is now the deciding factor" },
      { type: "p", text: "Meeting notes contain your most sensitive material: deals, hiring, strategy, 1:1s. Increasingly, security and legal teams won't approve a tool that ships all of that to an external cloud. On-device, open-source transcription sidesteps the entire review." },
      { type: "h2", text: "A simple shortlist test" },
      { type: "p", text: "Ask three questions: Does a bot join? Does my audio leave my device? Can I self-host if I need to? If the answers are no, no, and yes, you've found a tool your security team will actually approve." },
    ],
  },
  {
    slug: "otter-ai-alternatives",
    title: "5 Otter.ai Alternatives Worth Trying (Including a Private One)",
    description: "Otter.ai is popular but cloud-based with strict minute limits. Here are five alternatives, including a free, open-source, on-device option.",
    keyword: "otter ai alternatives",
    date: "2026-06-12",
    readMins: 6,
    body: [
      { type: "p", text: "Otter.ai is one of the best-known meeting transcribers, but two things send people looking for alternatives: the monthly transcription-minute caps on lower tiers, and the fact that every recording lives in Otter's cloud." },
      { type: "h2", text: "What to look for in an alternative" },
      { type: "ul", items: ["No (or generous) minute limits", "Clear data handling — ideally on-device", "Fair pricing for individuals", "Good export options"] },
      { type: "h2", text: "The alternatives" },
      { type: "ul", items: ["Ledgeur — open source, transcribes in your browser, free for individuals, no minute caps", "Fireflies — bot-based, strong CRM integrations, cloud", "Fathom — generous free tier, bot-based, cloud", "tl;dv — great for clipping highlights, bot-based, cloud", "Notta — multi-language, freemium with limits, cloud"] },
      { type: "h2", text: "The private option" },
      { type: "p", text: "If your reason for leaving Otter is privacy or cost, the on-device approach wins outright: Ledgeur never uploads your audio, has no minute caps, and is free for one person. You only pay when you want the record synced across devices, shared with a team, or open to your AI agents." },
    ],
  },
  {
    slug: "ai-meeting-notes-without-a-bot",
    title: "How to Get AI Meeting Notes Without a Bot Joining the Call",
    description: "Notetaker bots are awkward and a privacy risk. Here's how to capture AI meeting notes without any bot joining your Zoom, Meet or Teams call.",
    keyword: "ai meeting notes",
    date: "2026-06-12",
    updated: "2026-09-25",
    readMins: 8,
    body: [
      { type: "p", text: "You've seen it: halfway through a call, 'Otter.ai Notetaker has joined the meeting' pops up and everyone pauses. Notetaker bots are intrusive, they need broad calendar permissions, and they stream your audio to a vendor's servers." },
      { type: "h2", text: "Why bots exist" },
      { type: "p", text: "Cloud notetakers can't hear your meeting unless something joins it. So they dispatch a bot to sit in the call and stream the audio out. It works, but it's visible and it's a privacy trade-off." },
      { type: "h2", text: "The bot-free approach" },
      { type: "p", text: "Browsers can already capture the audio of a tab you're in. Ledgeur uses that: you share your meeting tab (with audio) and your microphone, and it transcribes the combined audio locally. No bot, nothing in the participant list, and no audio leaving your machine." },
      { type: "h2", text: "How to do it" },
      { type: "ul", items: ["Open your meeting in a browser tab (Zoom Web Client, Google Meet, Teams web)", "Open Ledgeur and click Record", "Share the meeting tab and tick 'Share tab audio'", "Get a live transcript and one-click notes when you're done"] },
      { type: "h2", text: "The practical setup that avoids missing half the call" },
      { type: "p", text: "The important setting is not the recorder; it is the tab-sharing picker. Choose the tab that is playing the call and explicitly enable its audio. That captures the other people. Add your microphone when the browser asks if you want your own voice in the record. Before the meeting starts, say a sentence and check that the transcript moves. It is much easier to correct a source setting in the first minute than to reconstruct a decision after the call." },
      { type: "p", text: "There are limits worth planning around. This route needs a browser that supports tab capture, and it only captures audio you are entitled to hear. A phone app, native desktop app or a Bluetooth headset can alter what the browser receives. For a meeting that matters, use a short test call with the same device and headphones. If tab capture is not available, import a recording you are allowed to make instead of pretending the tool heard something it did not." },
      { type: "h2", text: "Bot-free is not consent-free" },
      { type: "p", text: "A recorder being invisible in the participant list does not remove your obligation to follow the meeting's rules, employer policy or applicable law. Tell participants when a record is being made where that is required, agree who can access it, and do not use a convenience feature to sidestep a host's instruction. The point of a bot-free workflow is less social friction and more control over the audio path, not a way to record people covertly." },
      { type: "h2", text: "What to do with the draft" },
      { type: "p", text: "A transcript is normally working evidence, not the thing to broadcast. Pull out the decision, owner and date for the follow-up, then keep the fuller record with the narrower audience it deserves. If somebody corrects a name or quote, make that correction in the shared recap rather than leaving two competing versions in different tools." },
    ],
    faqs: [
      { question: "Can a browser record the audio from a meeting tab?", answer: "Browsers can offer tab or display capture with audio, but support and the exact picker vary. Test the browser and meeting platform you will actually use." },
      { question: "Will this capture my own voice?", answer: "Tab audio normally captures the call audio. Add microphone capture if you need your contribution in the transcript, and verify it on a short test recording." },
    ],
    sources: [
      { label: "MDN: Screen Capture API", href: "https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API" },
      { label: "Ledgeur browser support guidance", href: "https://www.ledgeur.com/transcribe" },
    ],
  },
  {
    slug: "how-to-transcribe-a-zoom-meeting",
    title: "How to Transcribe a Zoom Meeting for Free (Privately)",
    description: "A step-by-step guide to transcribing Zoom meetings for free, on your own device, without uploading anything to the cloud.",
    keyword: "zoom transcription",
    date: "2026-06-11",
    readMins: 5,
    body: [
      { type: "p", text: "Zoom's own transcription is fine, but it requires the right plan and it stores transcripts in Zoom's cloud. Here's how to transcribe any Zoom call for free and keep the transcript entirely on your device." },
      { type: "h2", text: "Step 1 — Run Zoom in the browser" },
      { type: "p", text: "Open the meeting with the Zoom Web Client (zoom.us/wc) so the call lives in a browser tab you can share." },
      { type: "h2", text: "Step 2 — Capture the tab audio" },
      { type: "ul", items: ["Open Ledgeur and click 'Record meeting'", "When prompted, choose the Zoom tab and tick 'Share tab audio'", "Allow your microphone so your own voice is captured too"] },
      { type: "h2", text: "Step 3 — Get your notes" },
      { type: "p", text: "Ledgeur transcribes the call in your browser as it happens. When you stop, click Generate notes for a summary, decisions and action items, then export Markdown. Nothing was uploaded to Zoom or anyone else." },
    ],
  },
  {
    slug: "how-to-transcribe-microsoft-teams-meetings",
    title: "How to Transcribe Microsoft Teams Meetings (No Teams Premium)",
    description: "Transcribe Microsoft Teams meetings for free without a Teams Premium licence — on-device, private, and exportable to Markdown.",
    keyword: "microsoft teams transcription",
    date: "2026-06-11",
    updated: "2026-09-25",
    readMins: 8,
    body: [
      { type: "p", text: "Teams' built-in transcription is gated behind licensing and stores everything in Microsoft 365. If you want a free, private transcript — or your IT policy forbids external notetaker clouds — here's a clean way to do it." },
      { type: "h2", text: "Use the Teams web app" },
      { type: "p", text: "Join the meeting at teams.microsoft.com so it runs in a shareable browser tab." },
      { type: "h2", text: "Capture and transcribe" },
      { type: "ul", items: ["Open Ledgeur and click Record", "Share the Teams tab and enable 'Share tab audio'", "Add your microphone so both sides are transcribed", "Everything is processed on your device — ideal for regulated industries"] },
      { type: "h2", text: "Why this works for compliance" },
      { type: "p", text: "Keeping a draft transcript on the device can reduce the number of systems that receive meeting content, but it does not settle a compliance review by itself. Your organisation may still have recording rules, retention rules, endpoint-management requirements or restrictions on local files. Treat local processing as an architectural fact to bring to the review, not as a substitute for the review." },
      { type: "h2", text: "What Teams already provides" },
      { type: "p", text: "Teams can record and transcribe meetings when the organiser's policy and meeting settings allow it. Microsoft says those controls can be managed by meeting policies, sensitivity labels and templates, and that transcripts and recordings are stored in the organiser's Microsoft 365 storage. That may be exactly the right answer when your team already has an approved retention and access model in Microsoft 365. It is not a reason to bypass the organiser's settings." },
      { type: "p", text: "Use a local transcript when the real requirement is different: you need a personal working note, you have permission to make one, and you do not want to send a second copy to another notetaker vendor. It is not a replacement for the official Teams record when the organisation needs the meeting artefact kept in its approved tenant." },
      { type: "h2", text: "A five-minute pre-flight check" },
      { type: "ol", items: ["Ask the organiser whether recording is permitted and whether Teams' own transcript is the record of authority.", "Join a short test in the Teams web client and confirm the tab picker exposes audio.", "Make sure the tab-audio and microphone indicators both move before the substantive discussion starts.", "Afterwards, review names, numbers and decisions against the recording before sharing a summary."] },
      { type: "h2", text: "If the capture is silent" },
      { type: "p", text: "Stop and diagnose before the meeting moves on. Check that you selected the Teams tab rather than the entire display, that tab audio was enabled in the browser picker, and that the call is playing through the selected browser. Do not fill a gap by guessing from a partial transcript. If local capture cannot be made reliably, use the organisation's approved Teams transcript or take manual minutes and state that limitation plainly." },
      { type: "p", text: "This is a better outcome than a confident-looking record with missing voices. The record should make its own limits obvious to the person who reads it later." },
    ],
    faqs: [
      { question: "Do I need Teams Premium to get a transcript?", answer: "Teams transcription availability depends on the meeting, policy and licensing configuration. Check the organiser's tenant settings; do not rely on a generic claim about a plan." },
      { question: "Where does a Teams transcript live?", answer: "Microsoft documents storage and access behaviour for Teams recordings and transcripts. Your organisation can apply its own policies on top of that." },
    ],
    sources: [
      { label: "Microsoft Learn: Teams recording and transcription overview", href: "https://learn.microsoft.com/en-us/microsoftteams/recording-transcription-overview" },
      { label: "Microsoft Support: live transcripts in Teams meetings", href: "https://support.microsoft.com/en-us/teams/meetings/start-stop-and-download-live-transcripts-in-microsoft-teams-meetings" },
    ],
  },
  {
    slug: "google-meet-transcription-guide",
    title: "Google Meet Transcription: A Free, Private Guide",
    description: "How to transcribe Google Meet calls for free without Workspace add-ons — on-device transcription and AI notes that stay private.",
    keyword: "google meet transcription",
    date: "2026-06-10",
    readMins: 4,
    body: [
      { type: "p", text: "Google Meet's transcription needs a paid Workspace tier and keeps transcripts in Google Drive. Ledgeur gives you a free alternative that runs in the same browser tab and keeps everything local." },
      { type: "h2", text: "Steps" },
      { type: "ul", items: ["Join your Meet call (it already runs in the browser)", "Open Ledgeur and click Record", "Share the Meet tab with 'Share tab audio' enabled", "Allow your mic so the whole conversation is captured"] },
      { type: "h2", text: "After the call" },
      { type: "p", text: "Generate notes with one click, edit the Markdown, and export or save it to your browser. Google never sees the transcript Ledgeur builds." },
    ],
  },
  {
    slug: "fireflies-vs-otter-vs-ledgeur",
    title: "Fireflies vs Otter vs Ledgeur: Which Meeting Notetaker?",
    description: "A clear comparison of Fireflies, Otter.ai and Ledgeur across privacy, pricing, the bot question and open source.",
    keyword: "ai meeting notes",
    date: "2026-06-10",
    readMins: 6,
    body: [
      { type: "p", text: "Fireflies and Otter are two of the most popular AI notetakers. Ledgeur takes a different architectural approach. Here's how they line up on the things that matter." },
      { type: "h2", text: "Bot vs no bot" },
      { type: "p", text: "Fireflies and Otter both rely on a bot joining your call (or a cloud recorder). Ledgeur captures the meeting tab's audio directly in your browser — no bot in the participant list." },
      { type: "h2", text: "Where your audio goes" },
      { type: "p", text: "Fireflies and Otter process and store recordings in their cloud. Ledgeur processes audio on your device and stores notes locally unless you export them." },
      { type: "h2", text: "Pricing" },
      { type: "ul", items: ["Fireflies — per-seat SaaS with a limited free tier", "Otter — freemium with monthly minute caps", "Ledgeur — free for one person with no minute caps; you pay only to sync, share or connect an agent"] },
      { type: "h2", text: "Open source" },
      { type: "p", text: "Fireflies and Otter are closed source. Ledgeur is MIT-licensed and self-hostable — the right pick if you need to audit the code or run it inside your own network." },
    ],
  },
];
